language: bash
sudo: false

services:
  - docker
addons:
  apt:
    packages:
      - docker-ce

script: 
  - bash deps-download.sh
  - bash build.sh

deploy:
  skip-cleanup: true
  provider: script 
  script: bash docker_push.sh
  on:
    branch: master 