language: bash
sudo: false
services:
  - docker
script: 
  - bash deps-download.sh
  - bash build.sh

deploy:
  skip-cleanup: true
  provider: script 
  script: bash docker_push
  on:
    branch: master 