version: "3"
services:
  spark-master:
    image: vfrank66/awsglue-local-dev:spark-master2.2.1-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - "SPARK_APPLICATION_JAR_LOCATION=/app"
  spark-worker-1:
    image: vfrank66/awsglue-local-dev:spark-worker2.2.1-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_APPLICATION_JAR_LOCATION=/app"
    links:
      - spark-master:spark-master
